name: "Run our own checks before merging"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setting up Nix
        uses: cachix/install-nix-action@v20
      - name: Run custom tests
        run: nix flake check
